name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/kovacs-akos/fireworkscrud:$IMAGE_TAG --tag ghcr.io/kovacs-akos/fireworkscrud:latest
        docker login ghcr.io -u kovacs-akos -p ${{secrets.GLCR_TOKEN}}
        docker push ghcr.io/kovacs-akos/fireworkscrud:$IMAGE_TAG
        docker push ghcr.io/kovacs-akos/fireworkscrud:latest
